Repository 2ndWatch/cloudendure-python, pull requests merged in 2019-09, with the labels that each got.

#57 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#59 Optimize SVG for size
  images/migration_pipeline.svg
Labels: documentation

#60 Update repo from transfer and make minor adjustments
  .stickler.yml
  Dockerfile
  Dockerfile-py38
  Makefile
  pydocmd.yml
  setup.py
  step/lambdas/copy_image.py
  step/lambdas/create_image.py
  step/lambdas/get_copy_status.py
  step/lambdas/get_image_status.py
  step/lambdas/get_instance_status.py
Labels: python

#67 Add cli auth and adjust user api token handling
  README.md
  cloudendure/api.py
  cloudendure/cloudendure.py
  cloudendure/config.py
Labels: enhancement, python

#68 Adjust CLI/config consolidation to avoid overwrites with empty values
  cloudendure/config.py
Labels: bug, python

#69 delete-image and terminate added
  cloudendure/cloudendure.py
Labels: aws, enhancement, python

#70 changes to support STS.
  cloudendure/cloudendure.py
  cloudendure/config.py
  step/iam.tf
  step/lambdas.tf
  step/lambdas/copy_image.py
  step/lambdas/find_instance.py
  step/lambdas/image_cleanup.py
  step/lambdas/split_image.py
  step/step-function.tf
Labels: aws, lambda, python

#72 Project provisioning
  cloudendure/api.py
  cloudendure/aws.py
  cloudendure/cloudendure.py
  cloudendure/constants.py
  pydocmd.yml
Labels: enhancement, python

#76 Add replication control for machines
  cloudendure/cloudendure.py
Labels: enhancement, python

#74 Add cookiecutter base handler
  Pipfile
  Pipfile.lock
  cloudendure/templates.py
Labels: enhancement, python

#80 0.1.1
  Makefile
  Pipfile.lock
  docs/API_README.md
  reference/swagger_config.json
  setup.py
Labels: enhancement, python, release, upgrade
