Repository 2ndWatch/cloudendure-python, pull requests merged in 2019-07, with the labels that each got.

#15 Update dependencies and adjust formatting
  Pipfile.lock
  cloudendure/api.py
  cloudendure/cloudendure.py
  lambda/handler.py
Labels: python, upgrade

#18 Add black to makefile
  Makefile
Labels: enhancement

#16 Check uses replica now. Launch looks up project_id and stops on replica.
  cloudendure/cloudendure.py
  cloudendure/config.py
Labels: enhancement, python

#17 Add typing throughout base project
  cloudendure/cloudendure.py
  cloudendure/config.py
  cloudendure/models.py
  lambda/copy_ami.py
  setup.py
Labels: enhancement, python
