Repository 2ndWatch/cloudendure-python, pull requests merged in 2019-08, with the labels that each got.

#20 copy_image and split_image support
  cloudendure/cloudendure.py
Labels: aws, enhancement, python

#26 Change image name to avoid blowup
  cloudendure/cloudendure.py
Labels: enhancement, python

#32 Add base event handler and implementation on launch function
  cloudendure/cloudendure.py
  cloudendure/config.py
  cloudendure/events.py
  cloudendure/exceptions.py
Labels: enhancement, python

#33 Move all configs to use Config for env and yaml
  cloudendure/cloudendure.py
  cloudendure/config.py
  cloudendure/utils.py
Labels: enhancement, python

#34 Update documentation with events entry and logos
  pydocmd.yml
Labels: documentation, enhancement

#35 Add typing throughout and import annotations from future
  cloudendure/api.py
  cloudendure/cloudendure.py
  cloudendure/cloudendure_api/configuration.py
  cloudendure/config.py
  cloudendure/events.py
  cloudendure/exceptions.py
  cloudendure/models.py
  cloudendure/utils.py
  lambda/copy_ami.py
  lambda/exceptions.py
  lambda/handler.py
Labels: enhancement, python

#38 Upgrade docker images and drop py3.6 support
  Dockerfile
  Dockerfile-py38
  README.md
  setup.py
Labels: docker, python, upgrade

#42 Remove launch types
  README.md
  cloudendure/cloudendure.py
  cloudendure/events.py
  setup.py
Labels: python

#43 Cross region support for copy_and_split. gen_terraform fixes
  cloudendure/cloudendure.py
  cloudendure/templates.py
  step/lambdas.tf
  step/lambdas/copy_image.py
  step/lambdas/get_copy_status.py
  step/lambdas/split_image.py
  step/step-function.tf
Labels: python

#50 Update config for single destination account
  README.md
  cloudendure/config.py
Labels: config, python

#52 Check for nonetype before iterating through image.tags
  cloudendure/cloudendure.py
Labels: bug, python

#56 Adjust init flow and user feedback
  cloudendure/api.py
  cloudendure/cloudendure.py
  cloudendure/exceptions.py
Labels: enhancement, python
